name: gnn_benchmark
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.6.0=hd77b12b_0
  - asttokens=3.0.0=py312haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h4b0e54e_0
  - brotli-python=1.0.9=py312h5da7b33_9
  - brotlicffi=1.0.9.2=py312h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.8.3=py312haa95532_0
  - cffi=1.17.1=py312h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - contourpy=1.3.1=py312h214f63a_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py312h885b0b7_0
  - decorator=5.2.1=py312haa95532_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py312haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.55.3=py312h827c3e9_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=py312haa95532_0
  - ipython=9.1.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.1=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=py312haa95532_0
  - jupyter_core=5.8.1=py312haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h827c3e9_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.0=h404307b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=h18467be_1
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib=3.10.6=py312haa95532_0
  - matplotlib-base=3.10.6=py312h43afe63_0
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.5=py312haa95532_0
  - numexpr=2.11.0=py312hdb065b2_0
  - numpy=2.3.1=py312h5f75535_0
  - numpy-base=2.3.1=py312h23d94f8_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.17=h35632f6_0
  - packaging=25.0=py312haa95532_0
  - pandas=2.3.2=py312ha5e6156_0
  - parso=0.8.4=py312haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py312hb328d1f_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py312h02ab6af_0
  - pure_eval=0.2.3=py312haa95532_0
  - pycparser=2.23=py312haa95532_0
  - pygments=2.19.1=py312haa95532_0
  - pyqt=6.7.1=py312h378bd72_2
  - pyqt6-sip=13.9.1=py312h02ab6af_2
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.11=h716150d_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h885b0b7_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=26.2.0=py312h5da7b33_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - requests=2.32.5=py312haa95532_0
  - scikit-learn=1.7.1=py312h3fbe716_0
  - scipy=1.16.0=py312h242c13b_0
  - seaborn=0.13.2=py312haa95532_3
  - setuptools=72.1.0=py312haa95532_0
  - sip=6.10.0=py312h5da7b33_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py312haa95532_0
  - sympy=1.14.0=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py312h827c3e9_1
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.6=h8880b57_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - lxml==6.0.1
      - multidict==6.6.4
      - nibabel==5.3.2
      - nilearn==0.12.1
      - propcache==0.3.2
      - pyparsing==3.2.4
      - torch-geometric==2.6.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - yarl==1.20.1
prefix: C:\Users\rakes\anaconda3\envs\gnn_benchmark
